Fix child comment overflowing
knowit/julekalender_frontend pull request #24
Opened 2021-09-20 17:58 UTC by dymbe

Issue #19

2021-09-20 18:23 UTC, Goddesen requested changes

2021-09-20 18:23 UTC, Goddesen commented on src/components/Posts/Post.tsx
> +      {showChildPosts && (<div className="space-y-2 min-w-0">
Ønsker meg en kommentar på hva som var feil og hvorfor dette fungerte.

2021-09-21 07:48 UTC, dymbe commented on src/components/Posts/Post.tsx
> +      {showChildPosts && (<div className="space-y-2 min-w-0">
La til kommentar nå, lmk om det er noe annet

2021-09-23 07:25 UTC, Goddesen approved these changes

2021-09-23 07:25 UTC, merged